<?php

// Generated by ShippingMethodSeeder

return array (
  'costs' => 
  array (
    'JNT' => 14000.0,
    'GOSEND' => 25000.0,
    'JNE' => 12000.0,
    'SICEPAT' => 15000.0,
    'KURIR_TOKO_DEKAT' => 10000.0,
    'KURIR_TOKO' => 15000.0,
    'KURIR_TOKO_JAUH' => 20000.0,
    'AMBIL_SENDIRI' => 0.0,
  ),
  'kurir_toko_costs' => 
  array (
    'less_than_5km' => 10000.0,
    '5_to_10km' => 15000.0,
    'more_than_10km' => 20000.0,
  ),
  'store_location' => 
  array (
    'name' => 'Azka Garden',
    'address' => 'Jl. Raya KSU, Tirtajaya, Kec. Sukmajaya, Kota Depok, Jawa Barat 16412',
    'latitude' => -6.4122794,
    'longitude' => 106.829692,
  ),
  'method_labels' => 
  array (
    'JNT' => 'J&T EZ',
    'GOSEND' => 'GoSend Sameday',
    'JNE' => 'JNE REG',
    'SICEPAT' => 'SiCepat BEST',
    'KURIR_TOKO_DEKAT' => 'Kurir Toko (<5km)',
    'KURIR_TOKO' => 'Kurir Toko (5-10km)',
    'KURIR_TOKO_JAUH' => 'Kurir Toko (>10km)',
    'AMBIL_SENDIRI' => 'Ambil Sendiri di Toko',
  ),
  'service_names' => 
  array (
    'JNT' => 'EZ',
    'GOSEND' => 'Sameday',
    'JNE' => 'REG',
    'SICEPAT' => 'BEST',
    'KURIR_TOKO_DEKAT' => 'Internal-Dekat',
    'KURIR_TOKO' => 'Internal',
    'KURIR_TOKO_JAUH' => 'Internal-Jauh',
    'AMBIL_SENDIRI' => '-',
  ),
  'defaults' => 
  array (
    'method' => 'JNT',
    'cost' => 14000.0,
    'free_shipping_threshold' => 100000,
    'tax_rate' => 0.11,
  ),
  'updated_at' => '2025-07-31 17:30:20',
  'updated_by' => 'mulyadafa',
);
